---

- name: Ensure logrotate is installed
  become: yes
  apt:
    name: logrotate
    state: present
  tags:
    - logrotate

- name: Configure logrotate defaults
  become: yes
  template:
    src: defaults.conf.j2
    dest: "{{ logrotate_conf_location }}/defaults"
  tags:
    - logrotate

# todo - we can easily override another logrotate file if we aren't careful with naming
- name: Ensure logrotate configuration files are present
  become: yes
  template:
    src: logFile.j2
    dest: "{{ logrotate_conf_location }}/{{ item.filename }}"
  loop: "{{ logrotate_files }}"
  when: logrotate_files
  tags:
    - logrotate
